### PR TITLE
Support multiple OOXML Packages in the tree view

### LINKED ISSUE #34: Analyzing multiple document
When i try to see multiple word document's `document.xml` file in order to compare these files and detect differences between `.xml` tags, plugin isn't allow to me. It's working like a toggle button. When i try to analyze another word document `.xml` files at the same time, old document's `.xml` files is closed by plugin. So, is there any way to visualize **different** two or more `.xml` file at the same time?

### LINKED ISSUE #40: Open OOXML Package in New Tab
Not sure, but it could be related to issue [#13](https://github.com/yuenm18/ooxml-viewer-vscode/issues/34).

It would be great to be able to work with multiple documents in _separate tabs_ _within the same Visual Studio Code window_. For example, when a user right-clicks, there should be an additional option of "Open OOXML Package in New Tab."

Currently, as a workaround, I have to place the files in _different_ folders and open a new Visual Studio Code window for the second file.

### PR DESCRIPTION
**Pull request by yuenm18**
Add the ability to show  multiple packages in the tree view. The parts are now cached at `<storage-uri>/cache/<hash-of-file-path>/...`,  so multiple packages can be opened in the same editor window without the parts overwriting each other.  The "Search Parts" is now shown when right clicking the package in the tree view. This resolves #34 and should also resolve #40.

### CODE REVIEW

**Comment by yuenm18** [comment]
@adamshakhabov, does this resolve your issue?
[ooxml-viewer-1.3.1.zip](https://github.com/yuenm18/ooxml-viewer-vscode/files/10763850/ooxml-viewer-1.3.1.zip)

**Comment by yuenm18** [comment]
@mikeebowen When you get the chance, can you update the animated gifs in the README and push them to this branch?

**Comment by mikeebowen** [comment]
@yuenm18 I have a lot on my plate right now, but I will make new gifs when I have time. 

If there will be a new release, we should add a file size limit. If you try to load a huge file e.g., a 1000 page Word document, the extension will just hang for hours. I can add this too, it should be a quick fix

**Comment by adamshakhabov** [comment]
> @adamshakhabov, does this resolve your issue? [ooxml-viewer-1.3.1.zip](https://github.com/yuenm18/ooxml-viewer-vscode/files/10763850/ooxml-viewer-1.3.1.zip)

I can't install this

image

```log
17/02/2023 20:04:48 - Microsoft VSIX Installer
17/02/2023 20:04:48 - -------------------------------------------
17/02/2023 20:04:48 - vsixinstaller.exe version:
17/02/2023 20:04:48 - 17.4.2120
17/02/2023 20:04:48 - -------------------------------------------
17/02/2023 20:04:48 - Command line parameters:
17/02/2023 20:04:48 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\temp\ooxml-viewer-1.3.1.vsix
17/02/2023 20:04:48 - -------------------------------------------
17/02/2023 20:04:48 - Microsoft VSIX Installer
17/02/2023 20:04:48 - -------------------------------------------
17/02/2023 20:04:48 - Initializing Install...
17/02/2023 20:04:48 - Extension Details...
17/02/2023 20:04:48 - 	Identifier         : ooxml-viewer
17/02/2023 20:04:48 - 	Name               : OOXML Viewer
17/02/2023 20:04:48 - 	Author             : yuenm18
17/02/2023 20:04:48 - 	Version            : 1.3.1
17/02/2023 20:04:48 - 	Description        : Displays the contents of OOXML files
17/02/2023 20:04:48 - 	Locale             : en-US
17/02/2023 20:04:48 - 	MoreInfoURL        : 
17/02/2023 20:04:48 - 	InstalledByMSI     : False
17/02/2023 20:04:48 - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
17/02/2023 20:04:48 - 
17/02/2023 20:04:48 - 	SignatureState     : Unsigned
17/02/2023 20:04:48 - 	Supported Products : 
17/02/2023 20:04:48 - 		Microsoft.VisualStudio.Code
17/02/2023 20:04:48 - 			Version : 
17/02/2023 20:04:48 - 			ProductArchitecture : x86
17/02/2023 20:04:48 - 
17/02/2023 20:04:48 - 	References         : 
17/02/2023 20:04:48 - Signature Details...
17/02/2023 20:04:48 - 	Extension is not signed.
17/02/2023 20:04:48 - 
17/02/2023 20:04:48 - Searching for applicable products...
17/02/2023 20:04:48 - Found installed product - Visual Studio Professional 2019
17/02/2023 20:04:48 - Found installed product - Visual Studio Professional 2022
17/02/2023 20:04:48 - Found installed product - Global Location
17/02/2023 20:04:49 - VSIXInstaller.NoApplicableSKUsException: One or more extensions are for Visual Studio Code. Try installing them in Visual Studio Code.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

```

**Comment by mikeebowen** [comment]
@adamshakhabov 

In the log you posted, it says
` C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\...`
and
 `VSIXInstaller.NoApplicableSKUsException: One or more extensions are for Visual Studio Code. Try installing them in Visual Studio Code.`

Which looks like you are trying to install the extension in Visual Studio instead of VS Code. Are you trying to install by double clicking on the .vsix? If so, then if you have Visual Studio installed it's likely that your default app for .vsix is the VS Installer and it's failing, because it needs to be installed on VS Code. If you click the ellipsis from the Extensions tab in VS Code, there is an option to install from VSIX. Installing there should work:
image

**Comment by adamshakhabov** [comment]
Wow🚀 @mikeebowen, thank you for the help. @yuenm18, yes, it works. Many thanks, guys!!!

**Comment by yuenm18** [comment]
> @yuenm18 I have a lot on my plate right now, but I will make new gifs when I have time.
> 
> If there will be a new release, we should add a file size limit. If you try to load a huge file e.g., a 1000 page Word document, the extension will just hang for hours. I can add this too, it should be a quick fix

@mikeebowen Thanks, no rush.

For the file size limit, were you referring to the size of the ooxml package itself (prevent unpacking it), the number of files inside the package (prevent unpacking it), or the size of each part (prevent formatting it)?

**Pull request merged**
